name: yks_app
description: YKS sınavına hazırlanan öğrenciler için geliştirilmiş kapsamlı bir mobil uygulama.
publish_to: 'none'
version: 1.0.3+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # En güncel ve stabil versiyonlar
  shared_preferences: ^2.2.3
  percent_indicator: ^4.2.3
  circular_countdown_timer: ^0.2.3
  animated_text_kit: ^4.2.2
  fl_chart: ^0.68.0
  intl: ^0.19.0 # Flutter 3.19+ ile uyumlu en güncel stabil versiyon
  google_mobile_ads: ^5.1.0
  in_app_purchase: ^3.2.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.1 # EN GÜNCEL STABİL VERSİYON
  timezone: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/icons/
  generate: true