name: yks_app
description: YKS sınavına hazırlanan öğrenciler için geliştirilmiş kapsamlı bir mobil uygulama.
publish_to: 'none'
version: 1.0.3+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Storage
  shared_preferences: ^2.2.2

  # UI Components
  percent_indicator: ^4.2.1
  circular_countdown_timer: ^0.2.3
  animated_text_kit: ^4.2.2
  

  # Charts & Graphics
  fl_chart: ^0.66.2

  # Date & Time
  intl: ^0.20.2

  # Ads & Monetization
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.13

  # Utilities
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # Assets
  assets:
    - assets/images/
    - assets/icons/

  # App configuration
  generate: true